### ISSUE TITLE
Modifiers of Datetime

### ISSUE THREAD

**Issue by LukasRychtecky** [andrewmcveigh/cljs-time#97] opened 2017-05-30 08:16 UTC
Hi,

thanks for creating this library! I really like it.

What you think about extending `DateTimeProtocol` with `set-hours`, `set-minutes`, `set-seconds` and `set-milliseconds`? I use them in my project, thus I can create a PR if you want.

**Comment by danielcompton** [comment] 2017-05-30 22:17
Dupe of #72.

**Comment by andrewmcveigh** [comment] 2017-05-31 12:00
Thanks @danielcompton 

Yep, as I mentioned in #72 

> I don't want to stray from the clj-time API. This library is purposefully a (as good as possible in js) mirror of the clj-time API, which in turn is based on the Joda-Time API.

**Closed** 2017-05-31 12:00 UTC
Labels: duplicate
