### ISSUE TITLE
unparse fails with [org.clojure/clojurescript "1.7.122"] due to clojure.string/replace

### ISSUE THREAD

**Issue by hipitihop** [andrewmcveigh/cljs-time#43] opened 2015-08-31 08:23 UTC
Tested with com.andrewmcveigh/cljs-time "0.3.11" and clojurescript 1.7.58 and earlier and the following test passes, but fails in 1.7.122 due to clojure.string/replace changes.

    (deftest default-basic-time
      (testing "Confirm base cljs-time :basic-time uses zero time, seconds & milliseconds"
        (let [formatter-no-time   (datef/formatters :basic-date)
              formatter-with-time (datef/formatters :basic-date-time)
              iso8601             "20150408"
              from-str            (datef/parse formatter-no-time iso8601)        ; instantiate UTC from string without time
              from-date           (datef/unparse formatter-with-time from-str)]  ; convert back to UTC string with time
          (is (instance? js/goog.date.UtcDateTime from-str))
          (is (= "20150408T000000.000Z" from-date) "We expect UTC time including milliseconds to be zero."))))

**Comment by malchmih** [comment] 2015-08-31 12:29
+1

**Comment by levand** [comment] 2015-09-01 20:40
+1

**Comment by andrewmcveigh** [comment] 2015-09-02 06:43
Thanks for the report.

This should be "fixed" in d8179d0ac364a9d3f12c32c0144f4810e68032e1 by using the old string/replace definition, until I merge in some bigger changes that shouldn't require string/replace anymore.

Released as `0.3.12`.

**Comment by malchmih** [comment] 2015-09-02 07:42
@andrewmcveigh Works for me, thank you!

**Comment by danielcompton** [comment] 2015-09-02 08:55
I didn't fully understand the root cause of this issue. Is it a bug in cljs that should be reported?

**Comment by andrewmcveigh** [comment] 2015-09-02 09:19
@danielcompton Not sure if it's bug or not, but it's a change in behaviour to align with jvm clojure[1].

I don't think this case is tested, so maybe it is a bug. I guess I'd need to better understand the motivation of the change to know if it's intentionally breaking this behaviour.

https://github.com/clojure/clojurescript/commit/3e146905999f9b9ffb249e139e266f845c4af34c

**Closed** 2015-09-09 09:03 UTC

**Comment by adwelly** [comment] 2015-10-09 14:29
I think I may have encountered something related to this:

Using [org.clojure/clojure "1.7.0"]
          [org.clojure/clojurescript "1.7.122"]
          [com.andrewmcveigh/cljs-time "0.3.14"]

using lein figwheel I can do the following in the repl
```
......(fighwheel launches)
Prompt will show when figwheel connects to your application
To quit, type: :cljs/quit
cljs.user=> (ns cljs.user (:require [cljs-time.format :as f][cljs-time.coerce :as c]))
;; This loads cljs-time format and cljs-time coerce, I can't seem to get (use ...) working.
cljs.user=> (def datefmt (f/formatter "dd-MM-yyyy")) ;; I create a custom formatter
#'cljs.user/datefmt
cljs.user=> (def atime (c/from-long 1400000000)) ;; and a datetime - sometime in 1970
#'cljs.user/atime
cljs.user=> atime
#object[Object 19700117T045320]
cljs.user=> (f/unparse datefmt atime)
#object[TypeError TypeError: Cannot read property 'call' of null] ;; <- something wrong
cljs.user=> (f/show-formatters)
#object[TypeError TypeError: Cannot read property 'call' of null] ;; <- show-formatters uses unparse too
cljs.user=>
```
I'm always open to the possibility that I'm doing something catastrophically daft, but this code was working with an earlier version of clojurescript a few months back.

**Comment by andrewmcveigh** [comment] 2015-10-09 14:39
It's probably related to https://github.com/andrewmcveigh/cljs-time/issues/41 & https://github.com/bhauman/lein-figwheel/issues/210 rather than this issue.

What version of figwheel are you on?

**Comment by adwelly** [comment] 2015-10-09 14:50
Just looked - figwheel 0.4.0
